development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://xvpqwortfvpinn:9f9d0d0ee21ae4598f155742a636fb32caa749592e1adc2ed5f951f85231e3a7@ec2-184-73-175-95.compute-1.amazonaws.com:5432/dcf3loigd1e9mn
  channel_prefix: sample_app_production
